[package]
name = "pest_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.0"
pest_derive = "2.0"
clap = { version= "4.0.18", features= ["derive"] }
pest_consume_macros = "1.1.0"